language: objective-c
osx_image: xcode7
xcode_project: MCConstants/MCConstants.xcodeproj
xcode_scheme: MCConstants
notifications:
    email: false
script:
    - xctool
      -project MCConstants/MCConstants.xcodeproj
      -scheme MCConstants
      -sdk iphonesimulator
      build
      test
      CODE_SIGN_IDENTITY=""
      CODE_SIGNING_REQUIRED=NO
      GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
      GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
    - bash <(curl -s https://codecov.io/bash)
